In [2]:
import tensorflow as tf

# Hello World

In [3]:
"""
 Hello World for tensorFlow
"""

# Create a Constant op

# The value returned by the constructor represents the output
# of the constant op
hello = tf.constant('Hello, Tensorflow!')

In [6]:
# Start tf session
sess = tf.Session()

In [7]:
print(sess.run(hello))

b'Hello, Tensorflow!'


# Basic Operation

In [8]:
"""
Basic Operations example using TensorFlow Library
"""

# Constant，数学运算
a = tf.constant(2)
b = tf.constant(3)

with tf.Session() as sess:
    print("a: %i" % sess.run(a), "b: %i" % sess.run(b))
    print("Addition with constants: %i" % sess.run(a + b))
    print("Multiplication with constants: %i" % sess.run(a * b))

a: 2 b: 3
Addition with constants: 5
Multiplication with constants: 6


In [10]:
# Basic Operations with variable as graph input
# 变量输入，数学运算
a = tf.placeholder(tf.int16)
b = tf.placeholder(tf.int16)

# Define some operations
add = tf.add(a, b)
mul = tf.multiply(a, b)

# Launch the default graph
with tf.Session() as sess:
    print("Additioan with variables: %i" %\
          sess.run(add, feed_dict={a: 2, b: 3}))
    print("Multilication with variables: %i" %\
          sess.run(mul, feed_dict={a: 2, b: 3}))

Additioan with variables: 5
Multilication with variables: 6


In [12]:
# 矩阵乘法
# Matrix Muliplication from TensorFlow official tutorial
# matrix1: 1x2, matrix: 2x1
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.], [2.]])
# 矩阵乘法
product = tf.matmul(matrix1, matrix2)

# 输出为ndarray object
with tf.Session() as sess:
    result = sess.run(product)
    print(result)

[[12.]]


# Eager API

In [3]:
"""
Eager模式：预先的Tensorflow为声明式(declarative)编程形式，Eager模式下为命令式（imperative）。
类似于Pytorch，当调用tf的函数的时候，会直接执行相应的操作并得到值。
Eager模式开启后无法关闭。
"""
import numpy as np
import tensorflow.contrib.eager as tfe

# Set Eager API
print('Setting Eager mode...')
tf.enable_eager_execution()

# Define constant tensors
print("Define constant tensors")
a = tf.constant(2)
print("a = %i" % a)
b = tf.constant(3)
print("b = %i" % b)

Setting Eager mode...
Define constant tensors
a = 2
b = 3


In [4]:
print("Mixing operations with Tensors and Numpy Arrays")

# Define constant tensors
a = tf.constant([[2., 1.], [1., 0.]], dtype=tf.float32)
print("Tensor:\n a=%s" % a)
b = np.array([[3., 0.], [5., 1.]], dtype=np.float32)
print("NumpyArray:\n b=%s" % b)

Mixing operations with Tensors and Numpy Arrays
Tensor:
 a=tf.Tensor(
[[2. 1.]
 [1. 0.]], shape=(2, 2), dtype=float32)
NumpyArray:
 b=[[3. 0.]
 [5. 1.]]


In [5]:
print("Runing operations, without tf.Session")

c = a + b
print("a + b = %s" % c)

d = tf.matmul(a, b)
print("a * b = %s" % d)

Runing operations, without tf.Session
a + b = tf.Tensor(
[[5. 1.]
 [6. 1.]], shape=(2, 2), dtype=float32)
a * b = tf.Tensor(
[[11.  1.]
 [ 3.  0.]], shape=(2, 2), dtype=float32)


In [7]:
print("Iterate through Tensor 'a':")
for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        print(a[i][j])

Iterate through Tensor 'a':
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
